### ISSUE TITLE
TypeError: Can't instantiate abstract class

### ISSUE THREAD

**Issue by Mattang-Tim** [hdkiller/Auto-GPT-SystemInfo#11]
@Brian-Webster @hdkiller Need a little help here:
[notice] To update, run: pip install --upgrade pip
  Not loading plugin AutoGPTBaiduSearch. Key 'AutoGPTBaiduSearch' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBaiduSearch) as the key.
  Not loading plugin AutoGPTBingSearch. Key 'AutoGPTBingSearch' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBingSearch) as the key.
  Not loading plugin AutoGPTBluesky. Key 'AutoGPTBluesky' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBluesky) as the key.
  Not loading plugin AutoGPTEmailPlugin. Key 'AutoGPTEmailPlugin' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTEmailPlugin) as the key.
  Not loading plugin PlannerPlugin. Key 'PlannerPlugin' was not found in plugins_config.yaml. Zipped plugins should use the class name (PlannerPlugin) as the key.
  Not loading plugin AutoGPTRandomValues. Key 'AutoGPTRandomValues' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTRandomValues) as the key.
  Not loading plugin AutoGPTSceneXPlugin. Key 'AutoGPTSceneXPlugin' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTSceneXPlugin) as the key.
  Not loading plugin AutoGPTTelegram. Key 'AutoGPTTelegram' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTTelegram) as the key.
  Not loading plugin AutoGPTTwitter. Key 'AutoGPTTwitter' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTTwitter) as the key.
  Not loading plugin AutoGPTWikipediaSearch. Key 'AutoGPTWikipediaSearch' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTWikipediaSearch) as the key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 117, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 131, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
  File "/app/autogpt/plugins/__init__.py", line 283, in scan_plugins
    loaded_plugins.append(a_module())
  File "/usr/local/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: Can't instantiate abstract class SystemInformationPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input

**Comment by Mattang-Tim** [comment]
[notice] To update, run: pip install --upgrade pip
  Not loading plugin AutoGPTBaiduSearch. Key 'AutoGPTBaiduSearch' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBaiduSearch) as the key.
  Not loading plugin AutoGPTBingSearch. Key 'AutoGPTBingSearch' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBingSearch) as the key.
  Not loading plugin AutoGPTBluesky. Key 'AutoGPTBluesky' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTBluesky) as the key.
  Not loading plugin AutoGPTEmailPlugin. Key 'AutoGPTEmailPlugin' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTEmailPlugin) as the key.
  Not loading plugin PlannerPlugin. Key 'PlannerPlugin' was not found in plugins_config.yaml. Zipped plugins should use the class name (PlannerPlugin) as the key.
  Not loading plugin AutoGPTRandomValues. Key 'AutoGPTRandomValues' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTRandomValues) as the key.
  Not loading plugin AutoGPTSceneXPlugin. Key 'AutoGPTSceneXPlugin' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTSceneXPlugin) as the key.
  Not loading plugin AutoGPTTelegram. Key 'AutoGPTTelegram' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTTelegram) as the key.
  Not loading plugin AutoGPTTwitter. Key 'AutoGPTTwitter' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTTwitter) as the key.
  Not loading plugin AutoGPTWikipediaSearch. Key 'AutoGPTWikipediaSearch' was not found in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTWikipediaSearch) as the key.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/autogpt/__main__.py", line 5, in <module>
    autogpt.cli.main()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
    rv = super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/autogpt/cli.py", line 117, in main
    run_auto_gpt(
  File "/app/autogpt/main.py", line 131, in run_auto_gpt
    config.plugins = scan_plugins(config, config.debug_mode)
  File "/app/autogpt/plugins/__init__.py", line 283, in scan_plugins
    loaded_plugins.append(a_module())
  File "/usr/local/lib/python3.10/site-packages/abstract_singleton/__init__.py", line 14, in __call__
    cls._instances[cls] = super().__call__(*args, **kwargs)
TypeError: Can't instantiate abstract class SystemInformationPlugin with abstract methods can_handle_report, can_handle_text_embedding, can_handle_user_input, handle_text_embedding, report, user_input
